Object.defineProperty(exports, '__esModule', { value: true });
var LOCAL_NAME = (exports.LOCAL_NAME = {
  IMAGE: 'image',
  LIST: 'list',
  OPTION: 'option',
  SECTION_LIST: 'section-list',
  SELECT_MULTIPLE: 'select-multiple',
  SELECT_SINGLE: 'select-single',
  TEXT_FIELD: 'text-field',
  BODY: 'body',
  FORM: 'form',
  HEADER: 'header',
  ITEM: 'item',
  SECTION_TITLE: 'section-title',
  SPINNER: 'spinner',
  TEXT_AREA: 'text-area',
  TEXT: 'text',
  VIEW: 'view',
});
var NODE_TYPE = (exports.NODE_TYPE = {
  ELEMENT_NODE: 1,
  ATTRIBUTE_NODE: 2,
  TEXT_NODE: 3,
  CDATA_SECTION_NODE: 4,
  ENTITY_REFERENCE_NODE: 5,
  ENTITY_NODE: 6,
  PROCESSING_INSTRUCTION_NODE: 7,
  COMMENT_NODE: 8,
  DOCUMENT_NODE: 9,
  DOCUMENT_TYPE_NODE: 10,
  DOCUMENT_FRAGMENT_NODE: 11,
  NOTATION_NODE: 12,
});
